### ISSUE TITLE
How to use in AWS Lambda

### ISSUE THREAD

**Issue by RodrigoTomeES** [mrhenry/polyfill-library#95]
Hi,

I used to use the original library in AWS coping the polyfills to the required folder as [I write in the original repo](https://pre.bigcrafters.com/api/polyfills) but I am trying to make the same with this new implementation and the code throw an error when trying to read meta.json although the file exists.

Any ideas?

```bash
2024-12-16T09:36:09.734Z	7e5b8f11-c22c-49a7-b058-2e852136a1a0	ERROR	Error: ENOENT: no such file or directory, open '/var/task/polyfills/__dist/meta.json'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async Object.listMeta (/var/task/chunks/6966.js:2923:28)
    at async getPolyfills (/var/task/chunks/6966.js:2456:24)
    at async generatePolyfillString (/var/task/chunks/6966.js:2608:27)
    at async consumePolyfillString (/var/task/chunks/6966.js:2584:19)
    at async handler (/var/task/pages/api/polyfills.js:193:28)
    at async Object.apiResolver (/var/task/chunks/1458.js:2993:9)
    at async Module.<anonymous> (/var/task/chunks/1458.js:123:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/polyfills/__dist/meta.json'
}
```

<img width="289" alt="Image" src="https://github.com/user-attachments/assets/2bbf4c7b-4628-4d92-bf58-753495c8dc40" />

**Comment by romainmenke** [comment]
I am unsure 🤔 


There is a new API to override the FS API's that are used by the library.
Maybe you can use those to debug?

in `sources.js`:

```js
/**
 * Set the file system implementation to use.
 * The default implementation uses the Node.js `fs` module.
 *
 * @param {readFile} readFile - A function that reads a file and returns a promise.
 * @param {createReadStream} createReadStream - A function that creates a read stream.
 */
function setFs(readFile, createReadStream) {
	fsImpl = {
		readFile,
		createReadStream
	};
}
```

```js
const fs = require('node:fs');
const polyfillLibrarySources = require('@mrhenry/polyfill-library/sourrces');

polyfillLibrarySources.setFs(
	(path, encoding) => {
		// Inspect what is going on here:
		console.log(path);
		if (path === '/var/task/polyfills/__dist/meta.json') console.log(fs.existsSync(path));

		return fs.promises.readFile(path, encoding);
	},
	fs.createReadStream
);
```

**Comment by RodrigoTomeES** [comment]
@romainmenke I already find the error. I could make a PR with the updated documentation if you want

**Comment by romainmenke** [comment]
> Because it throw an error that it doesn't exists. It seems that in the compiled code the source folder is removed.

Sorry, typo :)
Should have tested it.

This is the correct path: `require('@mrhenry/polyfill-library/lib/sources.js')`

----

> I already find the error, the /var/task is the default of the lambda.

Good to hear this!

---

> I could make a PR with the updated documentation if you want

The general issue is that you have a bundler and that the bundler doesn't include files loaded through file system API's, right?

So any `require()` or `import` would work fine and would be part of the bundle.
But anything loaded through `fs.readFile` is missing.

And to compensate you need to move those files around while also updating the relative position of the files.

I am a bit hesitant to include docs about this specifically for AWS lambda and I even removed that section when we did the hard fork. Not that there was anything wrong with the docs itself, but rather that this is overly specific to AWS lambda and that I can't test or maintain those docs.

I would be fine with having a separate docs section for integrations and deployments.

For example `docs/deployments/aws-lamda.md`

So feel free to open a PR with new a new doc.

The old Lambda docs you added can be found here: https://github.com/mrhenry/polyfill-library/blob/812ee5eb67ffd66f12ac6e13554d8851af045c59/README.md#aws-lambda

**Comment by RodrigoTomeES** [comment]
> The general issue is that you have a bundler and that the bundler doesn't include files loaded through file system API's, right?
> 
> So any require() or import would work fine and would be part of the bundle.
> But anything loaded through fs.readFile is missing.
> 
> And to compensate you need to move those files around while also updating the relative position of the files.

Yes, that's it.

> I would be fine with having a separate docs section for integrations and deployments.
> 
> For example docs/deployments/aws-lamda.md

Okay I will upload the documentation in that path
